import requests
import discord
from discord.ext import commands
import datetime
import openai
import asyncio
intents = discord.Intents.default()
bot = commands.Bot(command_prefix="/", intents=intents)
endpoint = "https://www.robotevents.com/api/v2/teams?number%5B%5D=51777H&myTeams=false"
headers = {
    "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMTI2ZjliZGZkMzA0OTllNjNiMDVmOWY5NDk0MzVkOWRkMjEyNDA1ZWI5YmIxNzBkMGY2M2Y1YmVkYzY0ZDA3YzM4Yjc3OGIxNjY1MDgxYTciLCJpYXQiOjE3MDE4MTUyOTIuNzQ1MjE5OSwibmJmIjoxNzAxODE1MjkyLjc0NTIyMywiZXhwIjoyNjQ4NTg2NDkyLjcyNjY4NSwic3ViIjoiMTI0NTA0Iiwic2NvcGVzIjpbXX0.FHAH30QfjvhBr2zvz_I7ipiAb7MyItdQrJDVtaFY69igy6sc96cIv2S1WNP_ORd6ZUnAIcpWG2RoABDmBHyAIzBLP3wkOY4bSqE4oG_FUe4DWfrdyPsYPmktrzKjbI8m4BwbtSthRfjS-MZeXHMdd-kPz2cQnZGmPK9lVqoXdf-_1Q0ers__LDrncxsG7sJIn6HmJ1zNlc8ZICjgpv6NksiPyXNjtChKN8JWvPHTTkmVayfGTc8pwmejsonl-_VNZ0GDK3WR2mcZttl4-kkVJTgiDGOApRa3L5q8u7JdGUrzP9fgB7xxC-GqdwFSuFzcaqVOaNA3dSRuTOFgjFlldfOkk3N5Ud_PsDCzRJ_WQaA_FMOYC3VNdRzvqzuMmSxj0nZn_NloMTL7PLtscSg97r7bPYunOmmdY690fMACPeQIQmReP7Mop2kc-0frf_fGg9ry3OLz2NUAwP2mRBCkuMndwt8DRRjodSLnF0pkCUy0ePPfUs5d4dUEvwmFD1lwBW09psn6BInCxtzMXMDBWW7GluIcI5tuNTRZ-JaQhbQHCVjD2wwFjBRF9AEq8ElyUxJ2t7uCdAh1Cnknj9YBJ5jyJHUiSk6qLO4kNm2rIIijHtyE-yYUow6Wbd2fJTiwHP_1YfTYrJ0KQcTXOiGwKZOgxlEnNoZWAWkLYYO3Ras"
}
response = requests.get(endpoint, headers=headers)
print(response.json())
